[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'self' https://*.warpcast.com https://warpcast.com https://*.farcaster.xyz"
    X-Frame-Options = "ALLOW-FROM https://warpcast.com"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/.well-known/farcaster-manifest.json"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*" 